/**
 * @description       : 
 * @author            : Dhanush Babu
 * @group             : 
 * @last modified on  : 03-01-2023
 * @last modified by  : Dhanush Babu
**/
public class ConstantsReviwerPortalDashboard {
   public static final string REVIEW_COMPLETED = 'Review Completed';
     public static final string UNDER_REVIEW = 'Under Review';
     public static final string SUBMITTED = 'Submitted';
}